# Core Colors
background            #1a120e
foreground            #f0dfd8
selection_foreground  #ffb68f
selection_background  #532201
cursor                #ffb68f
cursor_text_color     #1a120e

# Regular Colors
color0  #1a120e
color1  #ffb4ab
color2  #ffb68f
color3  #cec891
color4  #ffdbca
color5  #ffdbca
color6  #e6beab
color7  #f0dfd8

# Bright Colors
color8  #413732
color9  #ffb4ab
color10 #ffb68f
color11 #cec891
color12 #ffdbca
color13 #ffdbca 
color14 #e6beab
color15 #f0dfd8
