exec-once = waybar -c ~/.config/waybar/configs/"bintang default" -s ~/.config/waybar/style/"bintang default.css"
exec-once = swww-daemon
exec-once = dunst
exec-once = nm-applet --indicator
exec-once = blueman-applet
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
