general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = rgba(9ca3afff)
    col.inactive_border = rgba(4b5563aa)
    resize_on_border = false
    allow_tearing = false
    layout = dwindle
}

decoration {
    rounding = 10
    
    # The "Slab" Opacity
    active_opacity = 1.0
    inactive_opacity = 0.8

    shadow {
        enabled = false
    }

    blur {
        enabled = true
        size = 6
        passes = 4
        ignore_opacity = true
        new_optimizations = true
        xray = true
        
        # Frosty Grey Colors
        brightness = 1.0
        contrast = 1.0
        vibrancy = 0.0
    }
}
